#!/usr/bin/env node
import fs from 'fs';
import path from 'path';
import os from 'os';
import { execFileSync } from 'child_process';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.dirname(__dirname);
const configDir = path.join(os.homedir(), '.pernosco-mcp');
const installedHostScript = path.join(configDir, 'native-host.js');
const daemonScript = path.join(pkgRoot, 'dist', 'daemon.js');

if (process.argv.includes('--build-only')) {
  process.exit(0);
}

// Generate a self-contained native-host.js with the daemon path baked in.
// This script lives at ~/.pernosco-mcp/native-host.js (a stable location)
// so the native messaging manifest survives npm cache cleanup.
function generateNativeHost() {
  fs.mkdirSync(configDir, { recursive: true });

  const script = `#!/usr/bin/env node
// Auto-generated by pernosco-mcp postinstall. Do not edit.
import { openSync, closeSync } from 'fs';
import fs from 'fs/promises';
import path from 'path';
import http from 'http';
import { spawn } from 'child_process';

const CONFIG_DIR = ${JSON.stringify(configDir)};
const SERVER_JSON = path.join(CONFIG_DIR, 'server.json');
const DAEMON_SCRIPT = ${JSON.stringify(daemonScript)};
const HEALTH_TIMEOUT_MS = 2000;
const MAX_WAIT_MS = 10000;
const POLL_INTERVAL_MS = 100;

function delay(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

function checkHealth(port) {
  return new Promise(resolve => {
    const req = http.get(
      \`http://localhost:\${port}/health\`,
      { timeout: HEALTH_TIMEOUT_MS },
      res => { resolve(res.statusCode === 200); }
    );
    req.on('error', () => resolve(false));
    req.on('timeout', () => { req.destroy(); resolve(false); });
  });
}

async function readServerJson() {
  try {
    const raw = await fs.readFile(SERVER_JSON, 'utf8');
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

async function spawnDaemon() {
  const logPath = path.join(CONFIG_DIR, 'daemon.log');
  const fd = openSync(logPath, 'w');
  const child = spawn(process.execPath, [DAEMON_SCRIPT], {
    detached: true,
    stdio: ['ignore', fd, fd],
  });
  child.unref();
  closeSync(fd);
}

async function waitForDaemon() {
  const deadline = Date.now() + MAX_WAIT_MS;
  while (Date.now() < deadline) {
    await delay(POLL_INTERVAL_MS);
    const info = await readServerJson();
    if (info && await checkHealth(info.port)) {
      return info.port;
    }
  }
  throw new Error(\`Daemon failed to start within \${MAX_WAIT_MS}ms\`);
}

async function detectOrSpawn() {
  const info = await readServerJson();
  if (info && await checkHealth(info.port)) {
    return info.port;
  }
  await spawnDaemon();
  return await waitForDaemon();
}

function readNativeMessage(stream) {
  return new Promise((resolve, reject) => {
    const headerBuf = Buffer.alloc(4);
    let headerBytesRead = 0;

    function cleanup() {
      stream.removeListener('readable', readHeader);
      stream.removeListener('error', onError);
      stream.removeListener('end', onEnd);
    }
    function onError(err) { cleanup(); reject(err); }
    function onEnd() { cleanup(); reject(new Error('stdin closed before complete message')); }

    function readHeader() {
      const chunk = stream.read(4 - headerBytesRead);
      if (!chunk) return;
      chunk.copy(headerBuf, headerBytesRead);
      headerBytesRead += chunk.length;
      if (headerBytesRead < 4) return;
      cleanup();
      readBody(headerBuf.readUInt32LE(0));
    }

    function readBody(msgLen) {
      const bodyBuf = Buffer.alloc(msgLen);
      let bodyBytesRead = 0;

      function onBodyReadable() {
        const chunk = stream.read(msgLen - bodyBytesRead);
        if (!chunk) return;
        chunk.copy(bodyBuf, bodyBytesRead);
        bodyBytesRead += chunk.length;
        if (bodyBytesRead < msgLen) return;
        stream.removeListener('readable', onBodyReadable);
        stream.removeListener('error', onBodyError);
        stream.removeListener('end', onBodyEnd);
        resolve(JSON.parse(bodyBuf.toString('utf8')));
      }

      function onBodyError(err) {
        stream.removeListener('readable', onBodyReadable);
        stream.removeListener('end', onBodyEnd);
        reject(err);
      }
      function onBodyEnd() {
        stream.removeListener('readable', onBodyReadable);
        stream.removeListener('error', onBodyError);
        reject(new Error('stdin closed before message body'));
      }

      stream.on('readable', onBodyReadable);
      stream.on('error', onBodyError);
      stream.on('end', onBodyEnd);
      onBodyReadable();
    }

    stream.on('readable', readHeader);
    stream.on('error', onError);
    stream.on('end', onEnd);
  });
}

function writeNativeMessage(stream, obj) {
  const json = JSON.stringify(obj);
  const jsonBuf = Buffer.from(json, 'utf8');
  const header = Buffer.alloc(4);
  header.writeUInt32LE(jsonBuf.length, 0);
  stream.write(header);
  stream.write(jsonBuf);
}

async function main() {
  try {
    await readNativeMessage(process.stdin);
    const port = await detectOrSpawn();
    writeNativeMessage(process.stdout, { port });
  } catch (err) {
    writeNativeMessage(process.stdout, { error: err instanceof Error ? err.message : String(err) });
    process.exit(1);
  }
}

main();
`;

  fs.writeFileSync(installedHostScript, script, { mode: 0o755 });
  console.log(`pernosco-mcp: native host installed at ${installedHostScript}`);
}

function registerUnix() {
  let manifestDir;
  if (process.platform === 'linux') {
    manifestDir = path.join(os.homedir(), '.mozilla', 'native-messaging-hosts');
  } else if (process.platform === 'darwin') {
    manifestDir = path.join(os.homedir(), 'Library', 'Application Support', 'Mozilla', 'NativeMessagingHosts');
  } else {
    return false;
  }

  fs.mkdirSync(manifestDir, { recursive: true });
  const template = JSON.parse(fs.readFileSync(path.join(pkgRoot, 'native-host.json'), 'utf8'));
  template.path = installedHostScript;
  const outPath = path.join(manifestDir, 'pernosco_mcp_bridge.json');
  fs.writeFileSync(outPath, JSON.stringify(template, null, 2));
  console.log(`pernosco-mcp: native messaging host registered at ${outPath}`);
  return true;
}

function registerWindows() {
  const template = JSON.parse(fs.readFileSync(path.join(pkgRoot, 'native-host.json'), 'utf8'));
  template.path = installedHostScript;

  const resolvedManifest = path.join(configDir, 'native-host-resolved.json');
  fs.writeFileSync(resolvedManifest, JSON.stringify(template, null, 2));

  const regKey = 'HKCU\\Software\\Mozilla\\NativeMessagingHosts\\pernosco_mcp_bridge';
  try {
    execFileSync('reg', ['add', regKey, '/ve', '/t', 'REG_SZ', '/d', resolvedManifest, '/f'], { stdio: 'pipe' });
    console.log(`pernosco-mcp: native messaging host registered in registry (${regKey})`);
    return true;
  } catch (err) {
    console.warn(`pernosco-mcp: failed to write registry key: ${err.message}`);
    return false;
  }
}

try {
  generateNativeHost();
  if (process.platform === 'win32') {
    registerWindows();
  } else {
    if (!registerUnix()) {
      console.warn('pernosco-mcp: native messaging host registration not supported on this platform');
    }
  }
} catch (err) {
  console.warn(`pernosco-mcp: could not register native messaging host: ${err.message}`);
}
